### ISSUE TITLE
No module named 'azureml.dataprep'

### ISSUE THREAD

**Issue by andyhcy008** [Microsoft/PendletonDocs#14]
I followed the tutorial and install the SDK by:
-pip install azureml-dataprep

but it gave me a error when I tried to import the package into Jupyter Notebook
"No module named 'azureml.dataprep'"

The folder where azureml being installed looks like:
 Anaconda3/Lib/site-packages/azureml/dataprep/
 - _pycache_
 - api (another folder)
 - _init_.py
 - ThridPartyNotice.html

**Comment by davidjenMS** [comment]
@andyhcy008 if above reply doesn't address your issue, please feel free to re-activate
